---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: blog
  labels:
    app: blog
spec:
  rules:
  - host: blog.localhost
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: blog
              port:
                number: 80
---